package ch.wiss.project151formulaone;

import jakarta.persistence.*;

/**
 * Represents a team entity.
 */
@Entity
public class Team {

    /**
     * Represents the identifier for a team entity.
     *
     * The {@code id} field is annotated with {@code @Id} to indicate that it is the primary key for the entity. It is also
     * annotated with {@code @GeneratedValue} to specify the strategy for generating the identifier value. In this case,
     * the strategy is set to {@code GenerationType.IDENTITY}, which means that the identifier value will be automatically
     * generated by the underlying database.
     *
     * @see Team
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Represents the name of a team entity.
     *
     * The {@code name} field is annotated with {@code @Column} to specify the mapping to a database column. The {@code name} attribute
     * is set to "name" to indicate that this field is mapped to the "name" column in the database. The {@code nullable} attribute is set
     * to {@code false} to indicate that the "name" column cannot contain null values.
     *
     * @see Team
     */
    @Column(name = "name", nullable = false)
    private String name;

    /**
     * Represents the country of a team entity.
     *
     * The {@code country} field is annotated with {@code @Column} to specify the mapping to a database column. The {@code name} attribute
     * is set to "country" to indicate that this field is mapped to the "country" column in the database. The {@code nullable} attribute is set
     * to {@code false} to indicate that the "country" column cannot contain null values.
     *
     * @see Team
     */
    @Column(name = "country", nullable = false)
    private String country;

    /**
     * Retrieves the name of the team.
     *
     * @return The name of the team as a String.
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the name of the team.
     *
     * This method sets the name of the team using the provided string value.
     *
     * @param name The name of the team to be set.
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Retrieves the country of the team.
     *
     * This method returns the country of the team as a String.
     *
     * @return The country of the team as a String.
     */
    public String getCountry() {
        return country;
    }

    /**
     * Sets the country of the team.
     *
     * This method sets the country of the team using the provided string value.
     *
     * @param country The country of the team to be set.
     */
    public void setCountry(String country) {
        this.country = country;
    }

    /**
     * Retrieves the identifier of the team.
     *
     * This method returns the identifier of the team as a Long.
     *
     * @return The identifier of the team as a Long.
     */
    public Long getId() {
        return id;
    }
}
