CREATE TABLE driver (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name VARCHAR(256) NOT NULL,
    country VARCHAR(256) NOT NULL,
    team_id BIGINT
);

CREATE TABLE team (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name VARCHAR(256) NOT NULL,
    country VARCHAR(256) NOT NULL
);