INSERT INTO DRIVER
(NAME, COUNTRY, TEAM_ID) VALUES
                             ('Max Verstappen', 'Netherlands', 22),
                             ('Sergio Perez', 'Mexico', 22),
                             ('George Russel', 'United Kingdom', 23),
                             ('Lewis Hamilton', 'United Kingdom', 23),
                             ('Charles Leclerc', 'Monaco', 24),
                             ('Carlos Sainz', 'Spain', 24),
                             ('Oscar Piastri', 'Australia', 25),
                             ('Lando Norris', 'United Kingdom', 25),
                             ('Fernando Alonso', 'Spain', 26),
                             ('Lance Stroll', 'Canada', 26),
                             ('Esteban Ocon', 'France', 27),
                             ('Pierre Gasly', 'France', 27),
                             ('Logan Sargeant', 'United States', 28),
                             ('Alexander Albon', 'Thailand', 28),
                             ('Daniel Ricciardo', 'Australia', 29),
                             ('Yuki Tsunoda', 'Japan', 29),
                             ('Zhou Guanyu', 'Peoples Republic of China', 30),
                             ('Valtteri Bottas', 'Finland', 30),
                             ('Kevin Magnussen', 'Denmark', 31),
                             ('Nico Hulkenberg', 'Germany', 31),
                             ('Liam Lawson', 'New Zealand', 32),
                             ('Nyck De Vries', 'Netherlands', 32);